export const blogData = [
	{
		id: 1,
		title: "Giants of the Caribbean",
		date: "DATUM VRAGEN",
		content: "Onderwaterfotograaf en ambassadeur van het Wereld Natuurfonds maakte op alle continenten van de wereld prachtige foto’s van het leven",
		category: "Duurzaam",
		img: "GC.jpg",
	},
	{
		id: 2,
		title: "Online portal Hotel Jakarta",
		date: "DATUM VRAGEN",
		content: "Printvisie is voor veel horeca en hotels de partner in drukwerk. Bedrijven zoals Hilton, Dudok, Van der Valk en",
		category: "Online portal",
		img: "OJ.jpg",
	},
	{
		id: 3,
		title: "Ahoy 6-daagse Daily Bulletin",
		date: "DATUM VRAGEN",
		content: "Soms gaat het om snelheid en betrouwbaarheid en is het de gewoonste zaak van de wereld dat er goed gedrukt wordt.",
		category: "Logistiek",
		img: "AB.jpg",
	},
	// {
	// 	id: 4,
	// 	title: "What Is The Crypto Volatility Index (CVI)?",
	// 	date: "Dec. 8, 2022",
	// 	content: "The Crypto Volatility Index (CVI) is a decentralized solution used as a benchmark to track",
	// 	category: "Sponsored",
	// 	img: "4.jpg",
	// },
	// {
	// 	id: 5,
	// 	title: "What Is The Crypto Volatility Index (CVI)?",
	// 	date: "jan. 8, 2022",
	// 	content: "The Crypto Volatility Index (CVI) is a decentralized solution used as a benchmark to track",
	// 	category: "Sponsored",
	// 	img: "5.jpg",
	// },
	// {
	// 	id: 6,
	// 	title: "What Is The Crypto Volatility Index (CVI)?",
	// 	date: "Dec. 10, 2022",
	// 	content: "The Crypto Volatility Index (CVI) is a decentralized solution used as a benchmark to track",
	// 	category: "Sponsored",
	// 	img: "6.jpg",
	// },
];
