export const projectsData = [
	{
	  id: 1,
	  title: "Giants of the Caribbean",
	  category: "Duurzaam",
	  image: "gotc.jpg",
	  filterValue: "duurzaam",
	  toBeRemoved: false,
	  description: "Onderwaterfotograaf en ambassadeur van het Wereld Natuurfonds maakte op alle continenten van de wereld prachtige foto's van het leven in de zee. Hiermee wilde hij mensen inspireren om meer om onze wereld te geven.",
	  secondDescription: "Printvisie heeft samen met Vincent het hardcoverboek vormgeven. Hierbij is gekozen voor chloorvrij FSC papier van de Italiaanse papierfabrikant Fedrigoni en is een formaat gekozen waarbij minimaal papierafval plaatsvond.",
	  product: "Hardcover boek met stofomslag",
	  papier: "Symbol Tatami - Fedrigoni",
	  druk: "Offset op Komori Lithrone",
	  special: "Chloorvrij FSC papier, inclusief drukwerkbegeleiding",
	},
	{
	  id: 2,
	  title: "Online portal Hotel Jakarta",
	  category: "Online portal",
	  image: "ophj.jpg",
	  filterValue: "online portal",
	  toBeRemoved: false,
	  description: "Printvisie is voor veel horeca en hotels de partner in drukwerk. Bedrijven zoals Hilton, Dudok, Van der Valk en de restaurants van Debuut Horeca zijn al jarenlang klant.",
	  secondDescription: "Binnen een groot hotel werken al snel enkele honderden mensen die jaarlijks vele duizenden gasten verwelkomen. Hiervoor is veel drukwerk nodig. Vaak is het 'standaard drukwerk' welke op afroep geleverd kan worden. Hotel Jakarta in Amsterdam maakt gebruik van de online portal om hun standaard bestellingen te doen.",
	  product: "Online portal",
	  papier: "Eigen keuze vanuit portal",
	  druk: "On demand drukwerk op Kodak Nexpress",
	  special: " Ontwikkeld in eigen huis en aangepast speciaal voor Hotel Jakarta",
	},
	{
	  id: 3,
	  title: "Ahoy 6-daagse Daily Bulletin",
	  category: "Logistiek",
	  image: "add.jpg",
	  filterValue: "logistiek",
	  toBeRemoved: false,
	  description: "Soms gaat het om snelheid en betrouwbaarheid en is het de gewoonste zaak van de wereld dat er goed gedrukt wordt.",
	  secondDescription: "Voor onze relatie Ahoy verzorgen wij de dagkranten van de wieler zesdaagse. Net als een echte krantendrukkerij starten wij 's nachts de persen op met het laatste nieuws uit Ahoy en ontvangen de bezoekers van dit jaarlijkse evenement iedere dag een de 6 daagse Daily Bulletin.",
	  product: " Nieuwsbrief 3-luik",
	  papier: "Houtvrij offset",
	  druk: "Offset op Komori Lithrone",
	  special: "Betrouwbaar 's nachts binnen 6 uur leveren",
	  video: "https://www.youtube.com/embed/I9ZlfDeunAo?si=LMufWaD2bkdLmuYf",
	},
  ];
  